In [23]:
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv("D://Machine Learning//sampledata//test//heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [25]:
X = df.drop(columns='HeartDisease')
y = df['HeartDisease']

In [26]:
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up

In [27]:
ch_mean = X.loc[X['Cholesterol'] != 0]['Cholesterol'].mean()
ch_mean

244.6353887399464

In [28]:
X['Cholesterol']  = X['Cholesterol'].replace(0,ch_mean)

In [29]:
res_mean = X.loc[X['RestingBP'] != 0]['RestingBP'].mean()

In [30]:
X['RestingBP'] = X['RestingBP'].replace(0, res_mean)

In [31]:
X

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope
0,40,M,ATA,140.0,289.0,0,Normal,172,N,0.0,Up
1,49,F,NAP,160.0,180.0,0,Normal,156,N,1.0,Flat
2,37,M,ATA,130.0,283.0,0,ST,98,N,0.0,Up
3,48,F,ASY,138.0,214.0,0,Normal,108,Y,1.5,Flat
4,54,M,NAP,150.0,195.0,0,Normal,122,N,0.0,Up
...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110.0,264.0,0,Normal,132,N,1.2,Flat
914,68,M,ASY,144.0,193.0,1,Normal,141,N,3.4,Flat
915,57,M,ASY,130.0,131.0,0,Normal,115,Y,1.2,Flat
916,57,F,ATA,130.0,236.0,0,LVH,174,N,0.0,Flat
917,38,M,NAP,138.0,175.0,0,Normal,173,N,0.0,Up

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import  Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import  train_test_split

In [33]:
X = pd.get_dummies(X, columns=['Sex', 'ChestPainType','RestingECG', 'ExerciseAngina', 'ST_Slope'], drop_first='True', dtype='int')

In [34]:
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140.0,289.0,0,172,0.0,1,1,0,0,1,0,0,0,1
1,49,160.0,180.0,0,156,1.0,0,0,1,0,1,0,0,1,0
2,37,130.0,283.0,0,98,0.0,1,1,0,0,0,1,0,0,1
3,48,138.0,214.0,0,108,1.5,0,0,0,0,1,0,1,1,0
4,54,150.0,195.0,0,122,0.0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110.0,264.0,0,132,1.2,1,0,0,1,1,0,0,1,0
914,68,144.0,193.0,1,141,3.4,1,0,0,0,1,0,0,1,0
915,57,130.0,131.0,0,115,1.2,1,0,0,0,1,0,1,1,0
916,57,130.0,236.0,0,174,0.0,0,1,0,0,0,0,0,1,0
917,38,138.0,175.0,0,173,0.0,1,0,1,0,1,0,0,0,1

In [35]:
scaler = StandardScaler()
cols = ['Age','RestingBP', 'Cholesterol','MaxHR', 'Oldpeak']
X[cols] = scaler.fit_transform(X[cols])

In [36]:
X

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,-1.433140,0.414853,0.832529,0,1.382928,-0.832432,1,1,0,0,1,0,0,0,1
1,-0.478484,1.527192,-1.212922,0,0.754157,0.105664,0,0,1,0,1,0,0,1,0
2,-1.751359,-0.141317,0.719935,0,-1.525138,-0.832432,1,1,0,0,0,1,0,0,1
3,-0.584556,0.303619,-0.574892,0,-1.132156,0.574711,0,0,0,0,1,0,1,1,0
4,0.051881,0.971022,-0.931438,0,-0.581981,-0.832432,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,-0.902775,-1.253656,0.363389,0,-0.188999,0.293283,1,0,0,1,1,0,0,1,0
914,1.536902,0.637320,-0.968969,1,0.164684,2.357094,1,0,0,0,1,0,0,1,0
915,0.370100,-0.141317,-2.132437,0,-0.857069,0.293283,1,0,0,0,1,0,1,1,0
916,0.370100,-0.141317,-0.162048,0,1.461525,-0.832432,0,1,0,0,0,0,0,1,0
917,-1.645286,0.303619,-1.306750,0,1.422226,-0.832432,1,0,1,0,1,0,0,0,1

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [38]:
X_train

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
795,-1.220994,-0.697486,-0.086986,1,2.247488,-0.081956,1,0,1,0,1,0,0,0,0
25,-1.857431,-0.141317,-0.668720,0,1.618717,-0.832432,1,0,1,0,1,0,0,0,1
84,0.264027,0.971022,-0.593657,1,-0.464087,0.105664,1,0,0,0,1,0,1,1,0
10,-1.751359,-0.141317,-0.631188,0,0.203982,-0.832432,0,0,1,0,1,0,0,0,1
344,-0.266338,-0.697486,0.000000,1,-1.289349,-0.832432,1,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,-0.584556,-0.697486,0.175733,0,-1.053560,-0.832432,0,0,0,0,0,1,0,0,1
270,-0.902775,-0.697486,-0.368470,0,0.125386,-0.832432,1,0,0,0,1,0,0,0,1
860,0.688318,-0.141317,0.156967,0,0.282579,0.480902,1,0,0,0,1,0,1,0,1
435,0.688318,1.082256,0.000000,0,-0.739174,-0.832432,1,0,0,0,0,1,1,0,1
102,-1.433140,0.971022,2.765386,0,-0.267596,1.043759,0,0,0,0,1,0,0,1,0

In [39]:
from sklearn.linear_model import  LogisticRegression
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import  accuracy_score, classification_report, f1_score

In [40]:
models = {
    'Logistic Regression': LogisticRegression(solver='saga',max_iter=2000),
    'KNN': KNeighborsClassifier(n_neighbors=5),
    'Naive Bayes': GaussianNB(),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'SVM': SVC(kernel='rbf')
}

In [41]:
result = []

In [42]:
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    result.append({
        'model':name,
        'accuracy':round(acc,4),
        'f1-score':round(f1,4)
    })

In [43]:
result

[{'model': 'Logistic Regression', 'accuracy': 0.8641, 'f1-score': 0.8792},
 {'model': 'KNN', 'accuracy': 0.8587, 'f1-score': 0.8785},
 {'model': 'Naive Bayes', 'accuracy': 0.8478, 'f1-score': 0.8614},
 {'model': 'Decision Tree', 'accuracy': 0.8207, 'f1-score': 0.8374},
 {'model': 'SVM', 'accuracy': 0.837, 'f1-score': 0.8585}]

In [ ]:
# import joblib
# joblib.dump(models['Logistic Regression'], 'LR.pkl')
# joblib.dump(scaler,'scaler.pkl')
# joblib.dump(X.columns.tolist(), 'columns.pkl')

['columns.pkl']